### ISSUE TITLE
Beatport

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/beatporttagger#1]
Hi! I have error when install webview, how i can fix? And on windows vds (2016) button browser don't open directories

**Comment by Marekkon5** [comment]
Pywebview - what error is it? Try Python 3.6 - only working version for me on Windows.
Browse button - does anything show in log?

**Comment by atarbig** [comment]
pip install webview error: 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

**Comment by Marekkon5** [comment]
Could you please send the whole log/output

**Comment by atarbig** [comment]
[webview.txt](https://github.com/Marekkon5/beatporttagger/files/5466016/webview.txt)

**Comment by Marekkon5** [comment]
Hello, my bad, `webview` got included in `requirements.txt ` when generating, but my project uses `pywebview`. Please try installing on the latest commit. Thank you.

**Comment by atarbig** [comment]
all work fine, thanks. Please add release date (or year) in format 2020-10-30 (yyyy-mm-dd)

**Comment by Marekkon5** [comment]
It already is in that format for FLAC files. For MP3 it's split into 2 tags (year and date) and using the ID3 standard formatting.

**Comment by atarbig** [comment]
Great tagger! Thank you for your work. I'm joyful !

**Comment by Marekkon5** [comment]
Hello, there has been new update, which should improve the matches.
