### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/beatporttagger#11]
Hi, i was able successfully compile the app (v1.1.7) but whenever i'm trying to run the app i get the message below.
The UAC is already enabled on my Computer!

![Screenshot 2021-01-15 164306](https://user-images.githubusercontent.com/74199552/104740879-5f1a1380-5740-11eb-9968-38c5ad2d0e0f.jpg)

**Comment by bascurtiz** [comment]
@rosgr100 
Never seen that before - Just tested to compile and run - works all good, see: https://youtu.be/u1P56h7N_I0

**Comment by Marekkon5** [comment]
Try compiling with `--debug` and then running the binary in cmd. However i recommend running directly from source or our binaries.

**Comment by rosgr100** [comment]
I've managed to compile the app.
The problem probably occurred because i was using the Python 3.9.
Using the 3.7 solved the problem.
