### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/beatporttagger#13]
Hi! I happy will tester for you. In beatporttagger check search mode. Look for instance track : Alex Morelli - Crimson Idol. Make as file and check tagger. Version 1.1.7 not found ,  but version: beatporttagger.win10-vm-Levenshtein - it's ok! This is very important to improve the algorithm, you need to look at the reason

**Comment by Marekkon5** [comment]
Hello, while searching for the track manually on beatport.com we can't find it. We also noticed that Beatport recently did some changes to their search engine that make it worse. Could you try to send the search link with query you use to find it? Thank you.

**Comment by atarbig** [comment]
it's strange but today all tracks tagged succesfull. https://www.beatport.com/search?q=Alex+Morelli+-+Crimson+Idol . it's tag ok too with 1.1.7. Probably after updating search worked with errors and this was fixed on beatport

**Comment by Marekkon5** [comment]
There were issues with Beatport, everything should be working now.
