### ISSUE TITLE
Compiling the app with python-levenshtein.

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/beatporttagger#4]
Hi @Marekkon5 i saw that the new .exe is using the python-levenshtein, how can we build the app with python-levenshtein?

I'm asking this because i see this warning message when i start the app

> C:\Users\rosGR\AppData\Local\Temp\_MEI155882\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning

I don't know if that matters though!

Thank you!

**Comment by Marekkon5** [comment]
BasCurtiz was actually attempting this and wrote a nice guide, huge thanks to him:

How to remove python-levenhstein warning

In the sourcecode python-Levensthein is not included in requirements.txt.
When you build and run it, it will show a warning message:
“user warning: using slow pure-python sequencematcher. Install python-levenhstein to remove this warning”

Just to get rid of this message, it needs a chonk of 4.5gb to install,
while the speed of operation will be almost identical.

If you really want that, here's the link to download Visual Studio C++ tools:
http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe
Then, when installing:
Select Customize and select the Windows 8.1 and Windows 10 versions.

Afterwards:
- add python-Levenshtein==0.12.0 to the requirements.txt and do another pip install --user -r requirements.txt
- change hiddenimports=[], to hiddenimports=['python-Levenshtein'],
- build it again using pyinstaller --onefile beatporttagger.spec

#levenshtein

**Comment by rosgr100** [comment]
Thanks for the explanation!

I don't really care about the message but i was wondering if there is actually any difference if you build the app using the python Levenshtein.

Thanks for the help once again!

**Comment by rosgr100** [comment]
Just an update...

If you install the python-levenhstein wheel (whl) you don't have to install the Visual Studio C++ tools.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-levenshtein
