### ISSUE TITLE
Tagger window

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/beatporttagger#8]
Adjust the tagger window, the start button is not visible at the bottom of the screen
![q](https://user-images.githubusercontent.com/33702625/102624960-d23a6500-4155-11eb-80f4-00cfbe7712d6.JPG)

**Comment by bascurtiz** [comment]
What resolution is your screen ?

**Comment by atarbig** [comment]
1366 x 768

**Comment by atarbig** [comment]
please fix size
