### ISSUE TITLE
How to change the tag version to ID3v2.4

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/beatporttagger#9]
Hi @Marekkon5 would you please help me?
If it's easy, would you please guide me on what should i change to save the tags as ID3v2.4?

Thank you for the new additions by the way!

**Comment by bascurtiz** [comment]
@rosgr100 
We actually prefer ID3v2.3 due better compatibility.
If you want ID3v2.4 just use an app like Mp3tag and change settings to make it write to ID3v2.4, see [example.](https://i.imgur.com/eiwLcmv.png)
Load your tracks or folder into Mp3tag, select all, hit Save.
Bam, all are now converted to ID3v2.4.

**Comment by rosgr100** [comment]
Hi @bascurtiz, thanks for the answer.
This is exactly what i do now, i use the mp3tag to convert the tags.

The only reason i do that is Traktor. It seems that there is a problem with the Traktor and some tag values that they are not officially part of the Id3v2.3 for example %releasetime%. When there is any tag value saved in a file that is not officially supported by id3v2.3 Traktor is wiping it out if you have any of the two "write tags to files" option enabled in Traktor's preferences.
